## https://docs.junit.org/5.3.0-M1/user-guide/index.html#writing-tests-parallel-execution
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.classes.default=concurrent
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.timeout.default=10s
junit.jupiter.execution.timeout.lifecycle.method.default=30s
junit.jupiter.execution.timeout.test.method.default=10s
